version: 2

mkdocs:
  configuration: .readthedocs.mkdocs.yml
  fail_on_warning: false

formats: all

python:
  version: 3.7
  install:
    - method: setuptools
      path: doc/mkdocs
    - requirements: doc/mkdocs/requirements.txt