name: fate-test-command
on:
  repository_dispatch:
    types: [fate-test-command]

jobs:
  fate-test-command:
    runs-on: ubuntu-latest
    name: A job to exec fate test
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        id: create-comment
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            ## fate-test
            [![](https://img.shields.io/static/v1?style=flat-square&logo=github&label=action&message=fate-test&color=orange)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) [![](https://img.shields.io/static/v1?style=flat-square&logo=github&label=type-${{ github.event.client_payload.slash_command.args.named.type }}&message=name-${{ github.event.client_payload.slash_command.args.named.name }}&color=orange)](${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.client_payload.pull_request.number }}#issuecomment-${{ github.event.client_payload.github.payload.comment.id }})

      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          submodules: true
      
      - name: fate test
        id: fate-test
        uses: weiwee/fate-test-action@v1
        with:
          type: ${{ github.event.client_payload.slash_command.args.named.type }} 
          name: ${{ github.event.client_payload.slash_command.args.named.name }} 
      
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          comment-id: ${{ steps.create-comment.outputs.comment-id }}
          edit-mode: append
          body: |
            ### results
            ```
            ${{ steps.fate-test.outputs.body }}
            ```
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray